### ISSUE TITLE
Can't input 0,01 as entry

### ISSUE THREAD

**Issue by AdnanDervisevic** [jonathanp/react-formatted-number-input#2]
A bit of an annoying bug that is tricky, because the component runs parseFloat on every input, every time you enter `n,0`, the component will strip it down to `n`. I haven't been able to reproduce this in Jest yet, but in user testing it's very clear. 

The `parse `function is what messes with it. Not a trivial fix though, because parsing the number will strip it every time, unfortunately... Any suggestions? :)

**Comment by jonathanp** [comment]
I have an idea, will look into it this weekend if it's gonna be as rainy outside as the meteorologists say
